spring.application.name=week11

# Database Configuration
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/week11}
spring.datasource.username=${DB_USERNAME:yusuf}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
